<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Akademik\StudiMahasiswa;

class StudiMahasiswaSeeder extends Seeder
{
    public function run(): void
    {
        $dataStudi = [
            // ================== DATA SEMESTER GASAL 2025 ==================
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13021',
                'nama_matkul'      => 'DATABASE SYSTEMS',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 14,
                'nilai_uts'        => 82.00,
                'nilai_angka'      => 83.50,
                'nilai_huruf'      => 'A-',
                'bobot'            => 3.88,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13027',
                'nama_matkul'      => 'ALGORITHMS',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 13,
                'nilai_uts'        => 65.00,
                'nilai_angka'      => 68.00,
                'nilai_huruf'      => 'C+',
                'bobot'            => 2.63,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13028',
                'nama_matkul'      => 'FUNDAMENTAL PROGRAMMING',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 14,
                'nilai_uts'        => 75.00,
                'nilai_angka'      => 76.00,
                'nilai_huruf'      => 'B',
                'bobot'            => 3.02,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13032',
                'nama_matkul'      => 'TECHNOLOGY AND ETHICS',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 14,
                'nilai_uts'        => 88.00,
                'nilai_angka'      => 90.00,
                'nilai_huruf'      => 'A',
                'bobot'            => 4.00,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13036',
                'nama_matkul'      => 'STATISTICS',
                'sks'              => 2,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 12,
                'nilai_uts'        => 85.00,
                'nilai_angka'      => 86.00,
                'nilai_huruf'      => 'A',
                'bobot'            => 4.00,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Gasal 2025',
                'kode_matkul'      => 'TK13037',
                'nama_matkul'      => 'CALCULUS',
                'sks'              => 2,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 14,
                'jumlah_kehadiran' => 14,
                'nilai_uts'        => 55.00,
                'nilai_angka'      => 58.00,
                'nilai_huruf'      => 'C',
                'bobot'            => 2.02,
            ],

            // ================== DATA SEMESTER GENAP 2025 ==================
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK13030',
                'nama_matkul'      => 'NUMERICAL METHOD',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 15,
                'jumlah_kehadiran' => 15,
                'nilai_uts'        => null,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK13034',
                'nama_matkul'      => 'OPERATING SYSTEMS',
                'sks'              => 2,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 13,
                'jumlah_kehadiran' => 12,
                'nilai_uts'        => 33.00,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK13038',
                'nama_matkul'      => 'ALGEBRA & DISCRETE MATHEMATICS',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 15,
                'jumlah_kehadiran' => 12,
                'nilai_uts'        => 56.00,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK13039',
                'nama_matkul'      => 'INTRODUCTION TO ARTIFICIAL INTELLIGENCE',
                'sks'              => 2,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 15,
                'jumlah_kehadiran' => 14,
                'nilai_uts'        => 85.00,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK23007',
                'nama_matkul'      => 'DATA STRUCTURES',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 16,
                'jumlah_kehadiran' => 16,
                'nilai_uts'        => 73.00,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
            [
                'user_id'          => 1,
                'tahun_akademik'   => 'Genap 2025',
                'kode_matkul'      => 'TK23022',
                'nama_matkul'      => 'BACK-END PROGRAMMING',
                'sks'              => 4,
                'kelas'            => 'D',
                'status_matkul'    => 'B',
                'jumlah_pertemuan' => 15,
                'jumlah_kehadiran' => 15,
                'nilai_uts'        => 74.00,
                'nilai_angka'      => null,
                'nilai_huruf'      => null,
                'bobot'            => null,
            ],
        ];

        foreach ($dataStudi as $studi) {
            StudiMahasiswa::create($studi);
        }
    }
}